version: '3.8'
services:
  api-mtt:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./api:/app
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_NAME: mtt_db

  mysql:
    image: mysql:9.4            # Válido según Docker Hub
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./db_data/:/var/lib/mysql