#docker compose para la api de prt en python y mysql
version: '3.8'
services:
  api-prt:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - mysql
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_NAME: prt_db 

  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/:/var/lib/mysql