services:
  back:
    build:
      context: ./api-back/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=back_db
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ./api-back:/app
    command: >
      sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: back_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3020:3306"
    volumes:
      - ./db_data/:/var/lib/mysql