# Docker Compose para API de Carabineros en Python y MySQL
services:
  # Servicio de la API Carabineros
  api-carabineros:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5006:8000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_NAME=carabineros_db
    volumes:
      - ./api:/app
    depends_on:
      - db
  db:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carabineros_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3006:3306"
    volumes:
      - ./db_data/:/var/lib/mysql
