apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: desarrollo-tt
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-certificate: "arn:aws:acm:us-east-1:892797891584:certificate/bd0a274a-31e4-4394-be16-c6717e718399"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - host: demo.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obtener-permiso-app
            port:
              number: 80

  - host: panel.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: panel-decisiones-app
            port:
              number: 80

  - host: fiscalizadores.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fiscalizadores-app
            port:
              number: 80

  - host: propietarios.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: propietarios-app
            port:
              number: 80

  - host: api.jorgegallardo.studio
    http:
      paths:
      - path: /aach
        pathType: Prefix
        backend:
          service:
            name: aach-api
            port:
              number: 80
      
      - path: /carabineros
        pathType: Prefix
        backend:
          service:
            name: carabineros-api
            port:
              number: 80
      
      - path: /mtt
        pathType: Prefix
        backend:
          service:
            name: mtt-api
            port:
              number: 80
      
      - path: /prt
        pathType: Prefix
        backend:
          service:
            name: prt-api
            port:
              number: 80
      
      - path: /sgd
        pathType: Prefix
        backend:
          service:
            name: sgd-api
            port:
              number: 80
      
      - path: /sii
        pathType: Prefix
        backend:
          service:
            name: sii-api
            port:
              number: 80
      
      - path: /srcei
        pathType: Prefix
        backend:
          service:
            name: srcei-api
            port:
              number: 80
      
      - path: /tgr
        pathType: Prefix
        backend:
          service:
            name: tgr-api
            port:
              number: 80
      
      - path: /back
        pathType: Prefix
        backend:
          service:
            name: back-api
            port:
              number: 80