apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: desarrollo-tt
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # AWS ALB hostname autom√°tico (sin certificado SSL personalizado)
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789:certificate/xxxxx
    # alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: demo.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obtener-permiso-app
            port:
              number: 80

  - host: panel.jorgegallardo.studio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: panel-decisiones-app
            port:
              number: 80