apiVersion: apps/v1
kind: Deployment
metadata:
  name: propietarios-app
  namespace: desarrollo-tt
  labels:
    app: propietarios-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propietarios-app
  template:
    metadata:
      labels:
        app: propietarios-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: propietarios-app
        image: 892797891584.dkr.ecr.us-east-1.amazonaws.com/desarrollo-tt/propietarios-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: "https://api.jorgegallardo.studio"
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        resources:
          requests:
            memory: "1Gi"
            cpu: "75m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 300
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 300
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: propietarios-app
  namespace: desarrollo-tt
spec:
  type: ClusterIP
  selector:
    app: propietarios-app
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
