# Docker Compose para API de SRCEI en Python y MySQL
services:
  # Servicio de la API SRCEI
  api-srcei:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_NAME=srcei_db
    volumes:
      - ./api:/app
    depends_on: 
      - db
  db:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: srcei_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3001:3306"
    volumes:
      - ./db_data/:/var/lib/mysql
